### PR TITLE
Fix 'github' capitalization

### PR DESCRIPTION
**Pull request by 0joshuaolson1**

### CODE REVIEW

**Comment by mlrawlings** [comment]
I'm okay with this change, the lowercase was really just to be "stylistic".  But we should probably use the capitalization that GitHub prefers.

If we're going to make this change, we should probably change the case to "Docs" and "Try online" (or "Try Online"?) as well.

**Comment by 0joshuaolson1** [comment]
I see what you mean, but it's also annoying to let the style GitHub chose dictate the rest of the menu.

**Comment by 0joshuaolson1** [comment]
?

**Comment by tigt** [comment]
Closing this because the [header link capitalization _was_ changed to be correct](https://github.com/marko-js/website/blob/0a54ccc95d6f065b32d2af95c5b39fff0643a3a1/src/components/app-layout/components/layout-header/index.marko), at some point…

**Pull request closed without merging**
